### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by turret-detected** [turret-detected/CIS220#2]
---Necessary

- [x] log unencrypted characters

- [x] fix space/newline

- [x] fix whitebox tkinter issue (potentially use appJar file selection)
- [x] error message for bad file extension/no file selected
- [x] update labels with filepaths

---Nice things

- [ ] image banner
